baseurl: /august-hoegn
encoding: utf-8
incremental: true

collections:
  archives:
    name: Dokumente
    output: true
  compositions:
    name: Kompositionen
    output: true
    attributes:
      id: Dokumenten-Nummer
      datum: Datum
      find_spot: Fundort
  historical_works:
    name: Geschichtswerk
    output: true
  interviews:
    name: Interviews
    output: true
  photos:
    name: Fotos
    output: true
  correspondence:
    name: Korrespondenz
    output: true

defaults:
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: documents
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "compositions"
    values:
      layout: compositions
  -
    scope:
      path: ""
      type: "historical_works"
    values:
      layout: historical-works
  -
    scope:
      path: ""
      type: "interviews"
    values:
      layout: interviews

  -
    scope:
      path: ""
      type: "photos"
    values:
      layout: photos

  -
    scope:
      path: ""
      type: "correspondence"
    values:
      layout: correspondence

attributes:
  archives:
    id: Nummer
    datum: Datum
    find_spot: Fundort
  correspondence:
    id: Nummer
    title: Betreff
    date: Datum
    sender: Absender
    recipient: Empfänger
  interviews:
    id: Nummer
    title: Titel
    interviewter: Interview-Partner
    birthday: Geburtstag
    day_of_death: Todestag
    age: Alter
    relation: Beziehung zu Högn
    location: Ort
    datum: Datum
    duration: Dauer


exclude:
- "*.php"
- README.md

categories:
  - project
