baseurl: /august-hoegn
encoding: utf-8

collections:
  compositions:
    output: true
  historical_works:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "compositions"
    values:
      layout: compositions
      metaphor_image: kompositionen
      metaphor_text: Kompositionen
  -
    scope:
      path: ""
      type: "historical_works"
    values:
      layout: historical-works
      metaphor_image: geschichtswerk
      metaphor_text: Geschichtswerk

exclude:
- "*.php"
- README.md
