baseurl: /august-hoegn
encoding: utf-8

collections:
  compositions:
    name: Kompositionen
    output: true
  archives:
    name: Dokumente
    output: true
  historical_works:
    name: Geschichtswerk
    output: true
  interviews:
    name: Interviews
    output: true
  photos:
    name: Fotos
    output: true
  correspondence:
    name: Korrespondenz
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "compositions"
    values:
      layout: compositions
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: documents
  -
    scope:
      path: ""
      type: "historical_works"
    values:
      layout: historical-works
  -
    scope:
      path: ""
      type: "interviews"
    values:
      layout: interviews

  -
    scope:
      path: ""
      type: "photos"
    values:

  -
    scope:
      path: ""
      type: "correspondence"
    values:
      layout: correspondence

exclude:
- "*.php"
- README.md

categories:
  - project
