baseurl: /august-hoegn
encoding: utf-8

collections:
  compositions:
    name: Kompositionen
    output: true
  archives:
    name: Dokumente
    output: true
  historical_works:
    name: Geschichtswerk
    output: true
  interviews:
    name: Interviews
    output: true
  photos:
    name: Fotos
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "compositions"
    values:
      layout: compositions
      metaphor_image: kompositionen
      metaphor_text: Kompositionen
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: documents
      metaphor_image: dokumente
      metaphor_text: Dokumente
  -
    scope:
      path: ""
      type: "historical_works"
    values:
      layout: historical-works
      metaphor_image: geschichtswerk
      metaphor_text: Geschichtswerk
  -
    scope:
      path: ""
      type: "interviews"
    values:
      layout: interviews
      metaphor_image: interviews
      metaphor_text: Interviews

  -
    scope:
      path: ""
      type: "photos"
    values:
      layout: photos
      metaphor_image: leben
      metaphor_text: Fotos

exclude:
- "*.php"
- README.md
