<?php
// Startseite
$headline[] = array ('index', '1', 'Startseite');

// inhalt
$headline[] = array ('inhalt', '1', 'Inhalt der Homepage');

/**
 * Leben
 */
$headline[] = array ('leben', '1', 'Leben');
$headline[] = array ('leben-lebenslauf', '2', 'Lebenslauf');
$headline[] = array ('leben-biographie', '2', 'Biographie');

// Fotos mit August H&ouml;gns
$headline[] = array ('leben-hoegn-portrait', '2', 'Portrait-Fotos von August H&ouml;gn');
$headline[] = array ('leben-hoegn-gruppen', '2', 'August H&ouml;gn auf Gruppen-Fotos');
$headline[] = array ('leben-verwandte-bekannte', '2', 'Fotos von Verwandten und Bekannten');

// Fotos zur Zeit August H&ouml;gns
$headline[] = array ('leben-ruhmannsfelden-hoegn', '2', 'Ruhmannsfelden zur Zeit August H&ouml;gns');
$headline[] = array ('leben-pfarrkirche-hoegn', '2', 'Pfarrkirche St. Laurentius zur Zeit August H&ouml;gns');
$headline[] = array ('leben-volksschule-hoegn', '2', 'Volksschule Ruhmannsfelden zur Zeit August H&ouml;gns');

// Fotos aus der heutigen Zeit
$headline[] = array ('leben-grabstaetten', '2', 'Grabst&auml;tten');

/**
 * Werk
 */
$headline[] = array ('werk', '1', 'Werk');

$headline[] = array ('werk-kompositionen', '2', 'Kompositionen');
$headline[] = array ('werk-kompositionen-einzeln',  '3', '- alle Kompositionen');
$headline[] = array ('werk-kompositionen-fundorte', '3', 'Fundorte der Kompositionen');
$headline[] = array ('werk-aufnahmen', '3', 'Aufnahmen der Kompositionen');


$headline[] = array ('werk-arrangements', '2', 'Arrangements');

$headline[] = array ('werk-geschichtswerk', '2', 'Geschichtswerk');
$headline[] = array ('werk-geschichtswerk-ruhmannsfelden', '3', 'Geschichte von Ruhmannsfelden (&Uuml;berblick)');
$headline[] = array ('werk-geschichtswerk-ruhmannsfelden-html', '4', 'Geschichte von Ruhmannsfelden im HTML-Format');
$headline[] = array ('werk-geschichtswerk-zachenberg', '3', 'Geschichte von Zachenberg (&Uuml;berblick)');
$headline[] = array ('werk-geschichtswerk-zachenberg-html', '4', 'Geschichte von Zachenberg im HTML-Format');
$headline[] = array ('werk-geschichtswerk-feuerwehr', '3', 'Geschichte der Feuerwehr Ruhmannsfelden (&Uuml;berblick)');
$headline[] = array ('werk-geschichtswerk-feuerwehr-html', '4', 'Geschichte der Feuerwehr Ruhmannsfelden im HTML-Format');
$headline[] = array ('werk-geschichtswerk-zeitung', '3', 'Heimatkundliche Zeitungsartikel (&Uuml;berblick)');
$headline[] = array ('werk-geschichtswerk-zeitung-html',  '4', 'Heimatkundliche Zeitungsartikel im HTML-Format');

$headline[] = array ('werk-rezeptionen', '2', 'rezipierte Kompositionen');

/**
 * Projekt
 */
$headline[] = array ('projekt', '1', 'Projekt');

//  Projekt im &uuml;berblick
$headline[] = array ('projekt-dokumente', '2', 'Dokumente');
$headline[] = array ('projekt-dokumente-einzeln', '3', '- alle Dokumente');
$headline[] = array ('projekt-dokumente-fundorte', '3', 'Fundorte der Dokumente');

$headline[] = array ('projekt-buch', '2', 'Das Buch Der Mozart von Ruhmannsfelden');
$headline[] = array ('projekt-buch-praesentation', '2', 'Die Buchpr&auml;sentation');
$headline[] = array ('projekt-noten', '2', 'Noten der Josephi-Messe F-Dur op. 62');

$headline[] = array ('projekt-interviews', '2', 'Interviews mit Zeitgenossen von August H&ouml;gn');
$headline[] = array ('projekt-interviews-einzeln', '3', '- alle Interviews');

$headline[] = array ('projekt-korrespondenz', '2', 'Korrespondenz');
$headline[] = array ('projekt-korrespondenz-einzeln', '3', '- alle Briefe');

$headline[] = array ('projekt-wiederauffuehrungen', '2', 'Wiederauff&uuml;hrungen von Kompositionen August H&ouml;gns');
$headline[] = array ('projekt-josef-friedrich', '2', 'Autor Josef Friedrich im Portr&auml;t');
$headline[] = array ('projekt-dank', '2', 'Herzlichen Dank');

// Projekte im einzelnen */
$headline[] = array ('projekt-auffuehrungsmaterial', '2', 'Auff&uuml;hrungsmaterial f&uuml;r umliegende Kirchench&ouml;re');
$headline[] = array ('projekt-geschichtswerk-papier', '2', 'Geschichtswerk in Papierform');
$headline[] = array ('projekt-kopien-handschriften', '2', 'Kopien der Handschriften');

// Download
$headline[] = array ('download', '1', 'PDF-Downloadseite');

// Links
$headline[] = array ('links', '2', 'Links');

// G&auml;stebuch
$headline[] = array ('gaestebuch', '2', 'G&auml;stebuch');
$headline[] = array ('gaestebuch-formular', '3', 'G&auml;stebuch-Formular');

// Impressum
$headline[] = array ('impressum', '2', 'Impressum');

// Kontakt
$headline[] = array ('kontakt', '2', 'Kontakt');


$array_besetzung	= array(
  // Partituren
  'par' => 'Partituren',
  
  'dip' => 'Dirigier-Partitur',
  'orp' => 'Chor u. Orgel-Partitur',
  
  // Chöre
  'gch' => 'gemischter Chor',
  'fch' => 'Frauenchor',
  'mch' => 'M&auml;nnerchor',
  
  's' => 'Sopran',
  's1' => 'Sopran I',
  's2' => 'Sopran II',
  'a' => 'Alt',
  'a1' => 'Alt I',
  'a2' => 'Alt II',
  't' => 'Tenor',
  't1' => 'Tenor I',
  't2' => 'Tenor II',
  'b' => 'Bass',
  'b1' => 'Bass I',
  'b2' => 'Bass II',
  
  // Soli
  'sol' => 'Soli',
  
  'sso' => 'Sopran-Solo',
  'aso' => 'Alt-Solo',
  'tso' => 'Tenor-Solo',
  'bso' => 'Bass-Solo',
  
  // Streicher
  'str' => 'Streicher',
  
  'vl' => 'Violine',
  'vl1' => 'Violine I',
  'vl2' => 'Violine II',
  'vla' => 'Viola',
  'vc' => 'Violoncello',
  'cb' => 'Kontrabass',
  
  // Blechbläser
  'bbl' => 'Blechbl&auml;ser',
  
  'tr' => 'Trompete',
  'tr1' => 'Trompete I',
  'tr2' => 'Trompete II',
  'fho' => 'Fl&uuml;gelhorn',
  'aho' => 'Althorn',
  'tho' => 'Tenorhorn',
  'who1' => 'Horn I',
  'who2' => 'Horn II',
  'tbn' => 'Posaune',
  'tbn1' => 'Posaune I',
  'tbn2' => 'Posaune II',
  'bbd' => 'Bombardon',
  
  // Holzbläser
  'hbl' => 'Holzbl&auml;ser',
  
  'fl' => 'Fl&ouml;te',
  'fl1' => 'Fl&ouml;te I',
  'fl2' => 'Fl&ouml;te II',
  'cl' => 'Klarinette',
  'cl1' => 'Klarinette I',
  'cl2' => 'Klarinette II',
  'fag1' => 'Fagott I',
  'fag1' => 'Fagott II',
  
  // Orgel
  'org' => 'Orgel',
  
  'ped' => 'mit Pedal',
  'man' => 'manualiter',
  
  // Klavier
  'kla' => 'Klavier',
  
  'h2' => '2 h&auml;ndig',
  'h4' => '4 h&auml;ndig',
  
  // Schlagwerk
  'sch' => 'Schlagwerk',
  
  'timp' => 'Pauken',
);

$array_briefe_august_hoegn = array(
  'a' => 'Briefe von August H&ouml;gn',
  'b' => 'Briefe an August H&ouml;gn',
);

$array_dok_art = array(
  '1' => 'Brief',
  '2' => 'Zeitungsartikel',
  '3' => 'Sonstiges',
);

$array_dok_fundort = array(
  '1' => 'Reicheneder-Chronik',
  '2' => 'Pfarrarchiv',
  '3' => 'Beilage zum Notenmaterial',
  '4' => 'Briefe aus dem Besitz von Stephan Leitner',
  '5' => 'Schul-Chronik',
  '6' => 'Hegeringf&uuml;hrer 35/36',
  '7' => 'Chronik des Turnvereins Ruhmannsfelden',
  '8' => 'Gemeindearchiv',
  '9' => 'Personalakt',
  '10' => 'Spruchkammerakt',
  '99' => 'Sonstige Fundorte',
);

$array_kom_fundort = array(
 '1' => 'Notenschrank in der Pfarrkirche',
 '2' => 'Dachboden des linken Seitenschiffs',
 '3' => 'Wohnung des Herrn Franz Danziger',
 '4' => 'Pfarrhof St. Laurentius Ruhmannsfelden',
 '5' => 'Bayerische Staatsbibliothek M&uuml;nchen',
 '6' => 'Haus der S&auml;ngerin Mathilde Glasschr&ouml;der',
);

$array_kor_art = array(
 '1' => 'Brief',
 '2' => 'E-Mail',
 '3' => 'Telefonat',
);

$array_noten = array(
 '1' => 'Partitur',
 '11' => 'Partitur II',
 '2' => 'Singstimmen',
 '3' => 'Streicherstimmen',
 '4' => 'Bl&auml;serstimmen',
 '5' => 'Orgel',
 '6' => 'Klavier',
 '61' => 'Klavier zu 4 H&auml;nden',
);

$array_status = array(
  '1' => '',
  '2' => 'verloren',
);

$array_tabellen_sortierung = array(
  'kompositionen' => 'ssort',
  'komponisten' => 'nachname, vorname',
  'gattungen' => 'sortierung',
  'dokumente' => 'datum',
  'korrespondenz' => 'datum, id',
  'interviews' => 'datum',
  'wikiwerke' => 'titel',
);

$array_thematik = array(
  '1' => 'Kirchenmusik',
  '10' => 'Turnverein',
  '9' => 'Jagd',
  '2' => 'heimatkundlichen Zeitungsartikeln',
  '12' => 'Schule',
  '11' => 'NS-Zeit',
  '14' => 'Entnazifizierung',
  '15' => 'Pensionierung',
  '8' => 'Geschichte von Ruhmannsfelden',
  '3' => 'Geschichte von Zachenberg',
  '13' => 'Feuerwehr',
  '5' => '80. Geburtstag',
  '7' => 'private Korrespondenz',
  '6' => 'Tod von August H&ouml;gn',
  '4' => 'Auff&uuml;hrungen von Kompositionen',
  '99' => 'Sonstige Dokumente',
);

$array_tonart = array(
  '1' => 'C-Dur',
  '2' => 'c-moll',
  '3' => 'Des-Dur',
  '4' => 'cis-moll',
  '5' => 'D-Dur',
  '6' => 'd-moll',
  '7' => 'Es-Dur',
  '8' => 'es-moll',
  '9' => 'E-Dur',
  '10' => 'e-moll',
  '11' => 'F-Dur',
  '12' => 'f-moll',
  '13' => 'Fis-Dur',
  '14' => 'fis-moll',
  '15' => 'G-Dur',
  '16' => 'g-moll',
  '17' => 'As-Dur',
  '18' => 'gis-moll',
  '19' => 'A-Dur',
  '20' => 'a-moll',
  '21' => 'B-Dur',
  '22' => 'b-moll',
  '23' => 'H-Dur',
  '24' => 'h-moll',
);

 ?>